library(sqldf)
x<-read.csv2("household_power_consumption.txt")
y<-sqldf("Select * from x WHERE Date = '1/2/2007' OR Date = '2/2/2007'")
rm(x)
k<-paste(y$Date,y$Time,sep=" ")
j<-as.POSIXlt(k,format="%d/%m/%Y %H:%M:%S")
rm(k)
h<-as.numeric(as.character(y[[3]]))
sm1<-as.numeric(as.character(y[[7]]))
sm2<-as.numeric(as.character(y[[8]]))
sm3<-as.numeric(as.character(y[[9]]))
volt<-as.numeric(as.character(y[[5]]))
react<-as.numeric(as.character(y[[4]]))

png("plot4.png")
par(mfrow = c(2,2))

plot(j,h,type="n",main=NULL,xlab="",ylab="Global Active Power")
lines(j,h)

plot(j,volt,type="n",main=NULL,xlab="datetime",ylab="Voltage")
lines(j,volt)

plot(j,sm1,type="n",main=NULL,xlab="",ylab="Energy sub metering")
lines(j,sm1,col="black")
lines(j,sm2,col="red")
lines(j,sm3,col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),bty="n")

plot(j,react,type="n",main=NULL,xlab="datetime",ylab="Global_reactive_power")
lines(j,react)
dev.off()
