library(sqldf)
x<-read.csv2("household_power_consumption.txt")
y<-sqldf("Select * from x WHERE Date = '1/2/2007' OR Date = '2/2/2007'")
rm(x)
k<-paste(y$Date,y$Time,sep=" ")
j<-as.POSIXlt(k,format="%d/%m/%Y %H:%M:%S")
rm(k)
h<-as.numeric(as.character(y[[3]]))
sm1<-as.numeric(as.character(y[[7]]))
sm2<-as.numeric(as.character(y[[8]]))
sm3<-as.numeric(as.character(y[[9]]))

png("plot3.png")
plot(j,sm1,type="n",main=NULL,xlab="",ylab="Energy sub metering")
lines(j,sm1,col="black")
lines(j,sm2,col="red")
lines(j,sm3,col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()